### ISSUE TITLE
[BUG] Doesn't run in http mode anymore

### ISSUE THREAD

**Issue by mtrolley** [linuxserver/docker-quassel-web#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I believe this commit made it so the quassel-webserver only runs in HTTPS mode: https://github.com/linuxserver/docker-quassel-web/commit/889ad6d49a5580611eedb833a5618b62a2f277ab

The SWAG proxy conf expects http and and port 64080 though: https://github.com/linuxserver/reverse-proxy-confs/blob/master/quassel-web.subdomain.conf.sample

The instructions at the top of the reverse proxy config say to use an environment variable to set http mode but it does not work for me and I can't find any reference to the use of the `HTTPS` env var in this repo.

### Steps To Reproduce

Create the container with compose as shown below and note the logs show it's running in HTTPS mode. The reverse proxy config does not work with this.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: Docker official Ubuntu APT source.
```

### CPU architecture

x86-64

### Docker creation

```bash
name: compose
services:
  quasselweb:
    container_name: quassel-web
    environment:
      PGID: "1000"
      PUID: "1000"
      QUASSEL_CORE: quasselcore
      QUASSEL_PORT: "4242"
      TZ: US/Eastern
      URL_BASE: /quassel
    hostname: docker
    image: lscr.io/linuxserver/quassel-web:latest
    ports:
    - mode: ingress
      target: 64080
      published: "64080"
      protocol: tcp
    restart: unless-stopped
```
```


### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

QUASSEL_CORE set, injecting env variables into settings.cjs
[custom-init] No custom files found, skipping...
SETTINGS: Using /app/quassel-web/settings-env.cjs
quassel-webserver listening for https connections on port 64443
[ls.io-init] done.
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

QUASSEL_CORE set, injecting env variables into settings.cjs
[custom-init] No custom files found, skipping...
SETTINGS: Using /app/quassel-web/settings-env.cjs
quassel-webserver listening for https connections on port 64443
[ls.io-init] done.

```
```

**Comment by Danie10** [comment]
Wondering if mine is the same issue as it is setup for http as the hosting and reverse proxy is all behind a firewall. Mine has refused to connect since I updated today.

EDIT: Yes rolled back to older version and it works perfectly

**Comment by thespad** [comment]
Oops, this is an unintentional breaking change, we had a weird inconsistency where if you configured via env it set the listener to http without an option to change it and if you configured via file it defaulted to HTTPS with the option to change it.

We harmonised the config but the problem is there doesn't seem to be an option to listen on both http and HTTPS at the same time.

Let me have a look this afternoon and see what we can do, in the meantime either roll back, use a config file, or update your reverse proxy to connect over HTTPS

**Comment by mtrolley** [comment]
I see the fix tried to work, but get an error:
```
QUASSEL_CORE set, injecting env variables into settings.cjs
sed: -i requires an argument
/etc/s6-overlay/s6-rc.d/init-quassel-web-config/run: line 42: /app/quassel-web/settings-env.cjs: Permission denied
```
I think it's because I run as non-root and this config file is owned by root, but am guessing.

**Comment by thespad** [comment]
Can you open a new issue for this as it's different to the original problem.
