### ISSUE TITLE
No fallback to default value on ENV

### ISSUE THREAD

**Issue by sparklyballs** [linuxserver/docker-quassel-web#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team
when you give the option to set an ENV via docker run command you give the impression that it is something that can be turned off and on by removing the offending -e switch.
that however is not the case, in this example for instance..

https://github.com/linuxserver/docker-quassel-web/blob/master/root/etc/cont-init.d/30-config#L16

a user could decide they want to reverse proxy using folder method , then change their mind  at some stage and want to switch to subdomain.. they might think that just taking that env out will give them what they want to achieve, but the config file in the volume mount will still have the url base in it..

they will then have to manually edit the value.... which kind of defeats the object of having the env in the first place.

**Comment by CHBMB** [comment]
Good point, should be an easy enough fix.
